Zoom3Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Zoom3Web.Controllers
{
    public class AdminController : Controller
    {
        ZOOM3Entities db = new ZOOM3Entities();
        //
        // GET: /Admin/

        public ActionResult AdminPhotos(int? page)
        {
           
            var usuario = Convert.ToInt32(Session["UserId"]);

            var photos = db.Photo.ToList();

            var not = db.Notifications.Where(u => u.NOT_U_Id == usuario && u.NOT_Leido == false);
            ViewBag.noti = not;

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(photos.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult AdminUsers(int? page)
        {
            var users = db.UserData.ToList();

            var usuario = Convert.ToInt32(Session["UserId"]);
            var purchases = db.Purchases.Where(p => p.PUR_US_Id == usuario);
            ViewBag.purchases = purchases.Count();

            var not = db.Notifications.Where(u => u.NOT_U_Id == usuario && u.NOT_Leido == false);
            ViewBag.noti = not;

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Delete User Data in Cascade
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteUser(int id)
        {
            deleteNotifications(id);
            deletePhotos(id);
            deleteCreditCard(id);

            var users = db.UserData.Where(n => n.US_Id == id).Single();
            try
            {
                db.UserData.Remove(users);
                db.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                RedirectToAction("ErrorPage", "Error");
            }

            return View();
        }

        /// <summary>
        /// Delete Cascade Photo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeletePhoto(int id)
        {
            deleteNotificationsByPhoto(id);
            deletePurchasesByPhoto(id);
            deleteCartByPhoto(id);
            deleteFavouritesByPhoto(id);

            var photos = db.Photo.Where(n => n.PH_Id == id).Single();
            try
            {
                db.Photo.Remove(photos);
                db.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                RedirectToAction("ErrorPage", "Error");
            }

            return View();
        }

        /// <summary>
        /// Delete Notifications by User
        /// </summary>
        /// <param name="id"></param>
        public void deleteNotifications(int id){
            var not = db.Notifications.Where(n => n.NOT_U_Id == id).ToList();

            if (not.Count() > 0)
            {
                try
                {
                    foreach (var n in not)
                    {
                        db.Notifications.Remove(n);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }
               
        }

        /// <summary>
        /// Delete Photos By User
        /// </summary>
        /// <param name="id"></param>
        public void deletePhotos(int id)
        {
            var photos = db.Photo.Where(n => n.PH_Id == id).ToList();
            if (photos.Count() > 0)
            {
                try
                {
                    foreach (var ph in photos)
                    {
                        deletePurchasesByPhoto(ph.PH_Id);
                        deleteCartByPhoto(ph.PH_Id);
                        deleteFavouritesByPhoto(ph.PH_Id);
                        db.Photo.Remove(ph);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }
            
        }

        /// <summary>
        /// Delete Credit Card Data by User
        /// </summary>
        /// <param name="id"></param>
        public void deleteCreditCard(int id)
        {
            var card = db.CreditCard.Where(n => n.CC_U_Id == id).ToList();
            if (card.Count() > 0)
            {
                try
                {
                    foreach (var c in card)
                    {
                        db.CreditCard.Remove(c);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }
            
        }

        /// <summary>
        /// Delete Notifications By Photo
        /// </summary>
        /// <param name="id"></param>
        public void deleteNotificationsByPhoto(int id)
        {
            var not = db.Notifications.Where(n => n.NOT_PH_Id == id).ToList();

            if (not.Count() > 0)
            {
                try
                {
                    foreach (var n in not)
                    {
                        db.Notifications.Remove(n);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }

        }

        /// <summary>
        /// Delete Photo Purchases
        /// </summary>
        /// <param name="id"></param>
        public void deletePurchasesByPhoto(int id)
        {
            var purc = db.Purchases.Where(n => n.PUR_PH_Id == id).ToList();

            if (purc.Count() > 0)
            {
                try
                {
                    foreach (var p in purc)
                    {
                        db.Purchases.Remove(p);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }

        }

        /// <summary>
        /// Delete Shopping Cart By Photo
        /// </summary>
        /// <param name="id"></param>
        public void deleteCartByPhoto(int id)
        {
            var cart = db.Cart.Where(n => n.C_PH_Id == id).ToList();

            if (cart.Count() > 0)
            {
                try
                {
                    foreach (var c in cart)
                    {
                        db.Cart.Remove(c);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }

        }

        /// <summary>
        /// Delete Favourites By Photo
        /// </summary>
        /// <param name="id"></param>
        public void deleteFavouritesByPhoto(int id)
        {
            var fav = db.Favourites.Where(n => n.FAV_PH_Id == id).ToList();

            if (fav.Count() > 0)
            {
                try
                {
                    foreach (var f in fav)
                    {
                        db.Favourites.Remove(f);
                    }
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    RedirectToAction("ErrorPage", "Error");
                }
            }

        }


    }
}

Zoom3Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zoom3Web.Models;

namespace Zoom3Web.Views.Upload
{
    public class UploadController : Controller
    {

        ZOOM3Entities db = new ZOOM3Entities();

        public ActionResult Upload()
        {
            ViewBag.PH_CAT_Id = new SelectList(db.Category, "CAT_Id", "CAT_Description");
            ViewBag.PH_US_Id = new SelectList(db.UserData, "US_Id", "US_Email");

            var usuario = Convert.ToInt32(Session["UserId"]);
            var not = db.Notifications.Where(u => u.NOT_U_Id == usuario && u.NOT_Leido == false);
            ViewBag.noti = not;

            return View();
        }

        /// <summary>
        /// Save an Image into a DataBase
        /// </summary>
        /// <param name="formCollection"></param>
        /// <returns></returns>

        [HttpPost]
        public ActionResult Upload(FormCollection formCollection)
        {
            var user = Convert.ToInt32(Session["UserId"]);
            if (Request != null)
            {
                

                Photo ph = new Photo();
                HttpPostedFileBase file = Request.Files["PH_Image"];

                if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    string fileName = file.FileName;
                    string fileContentType = file.ContentType;
                    byte[] fileBytes = new byte[file.ContentLength];
                    file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);

                    ph.PH_CAT_Id = Convert.ToInt32(formCollection["PH_CAT_Id"]);
                    ph.PH_Description = formCollection["PH_Description"];
                    ph.PH_Title = formCollection["PH_Title"];
                    ph.PH_Price = Convert.ToDecimal(formCollection["PH_Price"]);
                    var carro = formCollection["PH_InMarket"];
                    bool inMarket = obtainCartValue(carro);
                    if (!userWithAccount(user, inMarket))
                    {
                        ViewBag.PH_CAT_Id = new SelectList(db.Category, "CAT_Id", "CAT_Description");
                        var not = db.Notifications.Where(u => u.NOT_U_Id == user && u.NOT_Leido == false);
                        ViewBag.noti = not;
                        ModelState.AddModelError("", "Para poner a la venta debe introducir un número de cuenta");
                        return View();
                    }
                    ph.PH_InMarket = Convert.ToBoolean(inMarket);
                    
                    ph.PH_FileName = fileName;
                    ph.PH_Image = fileBytes;
                    ph.PH_US_Id = Convert.ToInt32(Session["UserId"]);
                    ph.PH_UploadDate = DateTime.Now;

                    
                    try
                    {
                        db.Photo.Add(ph);
                        db.SaveChanges();

                        
                        var query = db.Photo.Where(u => u.PH_US_Id == user);
                        Session["PhotosNo"] = query.Count();
                        return RedirectToAction("Index", "Home");
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        RedirectToAction("ErrorPage", "Error");
                    }
                }
            }

            return View("Index", "Home");
        }

        /// <summary>
        /// Check If User has Account Number
        /// </summary>
        /// <param name="usuario"></param>
        /// <param name="inCart"></param>
        /// <returns></returns>
        public bool userWithAccount(int usuario, bool inCart)
        {
            bool result = false;

            //Check if photo have price
            if (inCart == true)
            {
                var account = db.CreditCard.Where(c => c.CC_U_Id == usuario);
                if (account.Count() > 0)
                {
                    var cuenta = account.Single();
                    if (cuenta.CC_AccountNumber != null && cuenta.CC_AccountNumber != "")
                    {
                        result = true;
                    }
                }
            }
            
            return result;

        }

        public bool obtainCartValue(string inCart)
        {
            bool result = false;
            if (inCart.StartsWith("t")) result = true;
            else result = false;

            return result;
        }

        /// <summary>
        /// Check if User has Account Number
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public ActionResult checkUserAccount(int? user)
        {
            var usuario = Convert.ToInt32(Session["UserId"]);
            JsonResult result = Json("error", JsonRequestBehavior.AllowGet);

            var dbUser = db.UserData.Find(usuario);
            var creditCard = db.CreditCard.Where(c=>c.CC_U_Id == usuario);
            //Check if User has Bank Dates
            if(creditCard.Count()>0){
                 var UsercreditCard = db.CreditCard.Where(c=>c.CC_U_Id == usuario).Single();
                //Check if user has account number
                 if (UsercreditCard.CC_AccountNumber != null)
                {
                    result = Json(new
                    {
                        modal = true
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    result = Json(new
                    {
                        modal = false
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                result = Json(new
                {
                    modal = false
                }, JsonRequestBehavior.AllowGet);
            }

           
            return result;
        }
    }
}

Zoom3Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Zoom3</title>

        <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/jquery.js"></script>
        <script src="~/Scripts/jquery-2.1.4.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <script src="~/Scripts/plugins/morris/morris-data.js"></script>
        <script src="~/Scripts/plugins/morris/raphael.min.js"></script>
        <script src="~/Scripts/plugins/morris/morris.min.js"></script>
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
   
    </head>
    <body>
        <div id="wrapper">
            <header>
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="~/Home/Index"><img src="~/Images/Zoom3LogoWhite.gif" style="width:63%;" alt="Zoom3"/></a>
                    </div>
                    @Html.Partial("_LoginPartial")
                    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                    
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        
                        <ul class="nav navbar-nav side-nav">
                            <li><img src="~/Images/LogoWhiteZ.gif" width="100" class="logo-z" /></li>
                            @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-fw fa-home"></i>Inicio</a></li>
                            <li class="dropdown">
                                <a href="#" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Categories <i class="fa fa-fw fa-caret-down"></i></a>
                                <ul id="demo" class="collapse">
                                    <li>@Html.ActionLink("Más Populares", "Popular", "Categories")</li>
                                    <li>@Html.ActionLink("Arquitectura", "Arquitecture", "Categories")</li>
                                    <li>@Html.ActionLink("Arte", "Art", "Categories")</li>
                                    <li>@Html.ActionLink("Cine", "Movies", "Categories")</li>
                                    <li>@Html.ActionLink("Comida", "Food", "Categories")</li>
                                    <li>@Html.ActionLink("Deporte", "Sport", "Categories")</li>
                                    <li>@Html.ActionLink("Música", "Music", "Categories")</li>
                                    <li>@Html.ActionLink("Naturaleza", "Nature", "Categories")</li>
                                    <li>@Html.ActionLink("Paisajes", "Landscape", "Categories")</li>
                                    <li>@Html.ActionLink("Personas", "People", "Categories")</li>
                                    <li>@Html.ActionLink("Transporte", "Transport", "Categories")</li>
                                    <li>@Html.ActionLink("Otros", "Other", "Categories")</li>
                                    @*<li><a href="/Categories/GenericCategory/1">Más Populares</a></li>
                                    <li><a href="/Categories/GenericCategory/3">Arquitectura</a></li>
                                    <li><a href="/Categories/GenericCategory/4">Arte</a></li>
                                    <li><a href="/Categories/GenericCategory/5">Cine</a></li>
                                    <li><a href="/Categories/GenericCategory/6">Comida</a></li>
                                    <li><a href="/Categories/GenericCategory/7">Deporte</a></li>
                                    <li><a href="/Categories/GenericCategory/10">Música</a></li>
                                    <li><a href="/Categories/GenericCategory/11">Naturaleza</a></li>
                                    <li><a href="/Categories/GenericCategory/12">Paisajes</a></li>
                                    <li><a href="/Categories/GenericCategory/13">Personas</a></li>
                                    <li><a href="/Categories/GenericCategory/14">Transporte</a></li>
                                    <li><a href="/Categories/GenericCategory/16">Otros</a></li>*@
                                </ul>
                            </li>
                            @*<li>@Html.ActionLink("Market", "Market", "Market")</li>*@
                            <li><a href="@Url.Action("Market", "Market")"><i class="fa fa-fw fa-dollar"></i>Market</a></li>
                            @if (Session["UserName"] != null)
                            {
                                @*<li>@Html.ActionLink("UpLoad", "Upload", "Upload")</li>*@
                                <li><a href="@Url.Action("UpLoad", "UpLoad")"><i class="fa fa-fw fa-upload"></i>Subir</a></li>
                                @*<li>@Html.ActionLink("Favourites", "Favourites", "Favourites")</li>*@
                                <li><a href="@Url.Action("Favourites", "Favourites")"><i class="fa fa-fw fa-star"></i>Favoritas</a></li>
                                if (Convert.ToInt32(Session["Rol"]) == 2)
                                {
                                    <li class="dropdown">
                                        <a href="#" data-toggle="collapse" data-target="#admin"><i class="fa fa-fw fa-wrench"></i>Administración<i class="fa fa-fw fa-caret-down"></i></a>
                                        <ul id="admin" class="collapse">
                                            <li>@Html.ActionLink("Administración de Usuarios", "AdminUsers", "Admin")</li>
                                            <li>@Html.ActionLink("Administración de Fotos", "AdminPhotos", "Admin")</li>
                                        </ul>
                                    </li>
                                   
                                }
                            }
                            <li><a href="@Url.Action("FAQ", "Home")"><i class="fa fa-fw fa-question-circle"></i>FAQ</a></li>
                            <li><a href="@Url.Action("Contact", "Home")"><i class="fa fa-fw fa-envelope-o"></i>Contacto</a></li>
                        </ul>   
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </header>
            <div id="page-wrapper">
                <div class="container-fluid">
                    @RenderSection("featured", required: false)
                    <section class="content-wrapper main-content clear-fix">
                        @RenderBody()
                    </section>
                </div>
            </div>
            @*<footer>
                <div class="content-wrapper">
                    <div class="float-left">
                        <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                    </div>
                </div>
            </footer>*@
        </div>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        
    </body>

</html>

Zoom3Web/Views/Shared/_ProfileMenu.cshtml
@{ int usId = Convert.ToInt32(Session["UserId"]); }
@{bool hasImage = Convert.ToBoolean(Session["ProfilePhoto"]);}
<div class="user-nav">
    <div class="row user-sup">
        <div class="col-md-2 col-sm-4 col-xs-4 image-responsive">
            <div class="thumbnail">
                <a href="#">
                    @if (hasImage == false)
                    {
                        <img src="~/Images/Foto 7-6-15 17 01 55.jpg" />
                    }
                    else
                    {
                        <img src="@Url.Action("GetImage", "Profile", new { id = usId })" alt="Hola" />
                    }
                </a>
            </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-6 name-responsive">
            <h2>@Session["UserName"] @Session["UserLastname"]</h2>
            <p>@Session["PhotosNo"] Photos</p>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-2 button-responsive">
            @Html.ActionLink("Editar Perfil", "EditProfile", "Profile", new { @class = "btn btn-default bot-prof" })
            @Html.ActionLink("Cambiar Foto Perfil", "ChangeProfileImage", "Profile", new { @class = "btn btn-default bot-prof" })
        </div>
    </div>
        <nav class="navbar" role="navigation">
            @*navbar-inverse*@
            <ul class="nav navbar-nav menu-usuario">
                <li>@Html.ActionLink("Mi Perfil", "ProfileInfo", "Profile")</li>
                <li>@Html.ActionLink("Mis Fotos", "MyPhotos", "Profile")</li>
                <li>@Html.ActionLink("Fotos en Venta", "MyMarket", "Profile")</li>
                <li>@Html.ActionLink("Mis Compras", "MyPurchases", "Profile")</li>
            </ul>
        </nav>

</div>


<style>
    #page-wrapper {
        padding: 0px;
    }

    .container-fluid {
        padding-right: 0px;
        padding-left: 0px;
        margin-right: 0;
        margin-left: 0;
    }
</style>